// Generated by CoffeeScript 1.9.3
(function() {
  var Regions, States, active, l, states, util,
    slice = [].slice;

  util = require('util');

  l = console.log.bind(console);

  Regions = (function() {
    function Regions(all) {
      this.all = all;
    }

    Regions.prototype._exit = function() {
      var args, ref, region, results, state;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      ref = this.all;
      results = [];
      for (region in ref) {
        state = ref[region];
        results.push(state._exit.apply(state, args));
      }
      return results;
    };

    Regions.prototype._exitDescend = function() {
      var args, ref, region, results, state;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      ref = this.all;
      results = [];
      for (region in ref) {
        state = ref[region];
        results.push(state._exitDescend.apply(state, args));
      }
      return results;
    };

    Regions.prototype._enter = function() {
      var args, next, ref, region, results, state;
      next = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      ref = this.all;
      results = [];
      for (region in ref) {
        state = ref[region];
        results.push(state._enter.apply(state, [next].concat(slice.call(args))));
      }
      return results;
    };

    Regions.prototype._enterDescend = function() {
      var args, ref, region, results, state;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      ref = this.all;
      results = [];
      for (region in ref) {
        state = ref[region];
        if (state[args[0]]) {
          results.push(state._enterDescend.apply(state, args));
        } else {
          results.push(state._enterDescend());
        }
      }
      return results;
    };

    Regions.prototype.trigger = function() {
      var args, ref, region, results, state;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      ref = this.all;
      results = [];
      for (region in ref) {
        state = ref[region];
        results.push(state.trigger.apply(state, args));
      }
      return results;
    };

    Regions.prototype.to = function() {
      var args, ref, region, results, state;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      ref = this.all;
      results = [];
      for (region in ref) {
        state = ref[region];
        results.push(state.to.apply(state, args));
      }
      return results;
    };

    return Regions;

  })();

  States = (function() {
    function States(conf) {
      var k, v;
      for (k in conf) {
        v = conf[k];
        this[k] = v;
      }
    }

    States.prototype._exit = function(keep, deep) {
      if (this._current) {
        keep || (keep = this._deepHistory || this._history);
        deep || (deep = this._deepHistory);
        this._current._exit(keep && deep, deep);
        this._current._exitDescend();
        if (keep) {
          this._historyState = this._current;
        }
        return delete this._current;
      }
    };

    States.prototype._exitDescend = function() {
      if (this.exit) {
        return this.exit();
      }
    };

    States.prototype._enter = function() {
      var nextState, nextSubstates, ref, ref1, ref2, ref3, ref4;
      nextState = arguments[0], nextSubstates = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (nextState && !this[nextState]) {
        throw "Invalid state " + nextState;
      }
      this._current = (ref = (ref1 = this[nextState]) != null ? ref1 : this._historyState) != null ? ref : this[(ref2 = (ref3 = this._default) != null ? ref3 : this._history) != null ? ref2 : this._deepHistory];
      delete this._historyState;
      return (ref4 = this._current)._enterDescend.apply(ref4, nextSubstates);
    };

    States.prototype._enterDescend = function() {
      var nextSubstates;
      nextSubstates = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      if (this.enter) {
        this.enter();
      }
      if (nextSubstates[0] || this._default || this._historyState || this._history || this._deepHistory) {
        return this._enter.apply(this, nextSubstates);
      }
    };

    States.prototype.to = function() {
      var states;
      states = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      this._exit();
      return this._enter.apply(this, states);
    };

    States.prototype.on = function() {};

    States.prototype.trigger = function(e) {
      this.on(e, this.to.bind(this));
      if (this._current) {
        return this._current.trigger(e);
      }
    };

    return States;

  })();

  states = new States({
    _default: 'operational',
    operational: new States({
      _deepHistory: 'stopped',
      enter: function() {
        return l("> operational");
      },
      exit: function() {
        return l("< operational");
      },
      on: function(e) {
        if (e === 'flip') {
          return states.to('flipped');
        }
      },
      stopped: new States({
        enter: function() {
          return l("> stopped");
        },
        exit: function() {
          return l("< stopped");
        },
        on: function(e) {
          if (e === 'play') {
            return states.operational.to('active', 'running');
          }
        }
      }),
      active: new Regions({
        main: active = new States({
          _default: 'paused',
          enter: function() {
            return l("> active");
          },
          exit: function() {
            return l("< active");
          },
          running: new States({
            enter: function() {
              return l("> running");
            },
            exit: function() {
              return l("< running");
            },
            on: function(e) {
              if (e === 'pause') {
                return active.to('paused');
              }
            }
          }),
          paused: new States({
            enter: function() {
              return l("> paused");
            },
            exit: function() {
              return l("< paused");
            },
            on: function(e) {
              if (e === 'play') {
                return active.to('running');
              }
            }
          })
        }),
        light: new States({
          enter: function() {
            return l("> light");
          },
          exit: function() {
            return l("< light");
          }
        })
      })
    }),
    flipped: new States({
      enter: function() {
        return l('> flipped');
      },
      exit: function() {
        return l('< flipped');
      },
      on: function(e) {
        if (e === 'flip') {
          return states.to('operational');
        }
      }
    })
  });

  states.to(states._default);

  states.trigger('play');

  states.trigger('pause');

  states.trigger('flip');

  states.trigger('flip');

}).call(this);
